resource "aws_sagemaker_model_package_group" "purchase_propensity" {
  model_package_group_name        = var.model_package_group_name
  model_package_group_description = "Purchase propensity models generated by model_train."

  tags = {
    Project = var.project_name
  }
}
