resource "aws_sagemaker_model_package_group" "purchase_propensity" {
  model_package_group_name        = var.model_package_group_name
  model_package_group_description = "Purchase propensity models generated by model_train."

  tags = {
    Project = var.project_name
  }
}

resource "aws_sagemaker_pipeline" "model_train" {
  pipeline_name         = "${var.project_name}-model-train"
  pipeline_display_name = "${var.project_name}-model-train"
  role_arn              = aws_iam_role.sagemaker_pipeline.arn

  pipeline_definition = local.sagemaker_pipeline_definition

  tags = {
    Project = var.project_name
    Service = "model-train"
  }
}

resource "null_resource" "model_train_pipeline_execution" {
  count = var.trigger_training_pipeline ? 1 : 0

  triggers = {
    image_tag      = var.image_tag
    pipeline_name = aws_sagemaker_pipeline.model_train.pipeline_name
  }

  provisioner "local-exec" {
    command = <<-EOT
      aws sagemaker start-pipeline-execution \
        --region ${var.aws_region} \
        --pipeline-name ${aws_sagemaker_pipeline.model_train.pipeline_name} \
        --pipeline-execution-display-name train-${var.image_tag} \
        --pipeline-parameters Name=ImageTag,Value=${var.image_tag}
    EOT
  }

  depends_on = [
    aws_s3_object.training_events,
    aws_s3_object.training_products,
    aws_sagemaker_pipeline.model_train,
  ]
}
