resource "aws_sagemaker_model_package_group" "purchase_propensity" {
  model_package_group_name        = var.model_package_group_name
  model_package_group_description = "Purchase propensity models generated by model_train."

  tags = {
    Project = var.project_name
  }
}

resource "aws_sagemaker_model_package_group" "integration" {
  model_package_group_name        = "${var.project_name}-integration-model-group"
  model_package_group_description = "Isolated SageMaker Model Registry group for integration tests."

  tags = {
    Project = var.project_name
    Purpose = "integration-tests"
  }
}
