variable "aws_region" {
  description = "AWS region where the training infrastructure will be deployed."
  type        = string
  default     = "us-east-1"
}

variable "project_name" {
  description = "Prefix used to name shared infrastructure resources."
  type        = string
  default     = "personalization"
}

variable "image_tag" {
  description = "Docker image tag generated by the CI pipeline and pushed to ECR."
  type        = string
}

variable "training_data_prefix" {
  description = "S3 prefix where events.csv and products.csv are stored."
  type        = string
  default     = "training-data"
}

variable "ecs_task_cpu" {
  description = "CPU units for the ECS Fargate training task."
  type        = string
  default     = "1024"
}

variable "ecs_task_memory" {
  description = "Memory in MiB for the ECS Fargate training task."
  type        = string
  default     = "2048"
}

variable "model_package_group_name" {
  description = "SageMaker Model Registry group for purchase propensity models."
  type        = string
  default     = "purchase-propensity-model-group"
}

variable "ecs_service_desired_count" {
  description = "Desired task count for the model_train ECS service. Use 0 to avoid automatic restarts."
  type        = number
  default     = 0
}

variable "ecs_autoscaling_min_capacity" {
  description = "Minimum number of tasks for model_train ECS service autoscaling."
  type        = number
  default     = 0
}

variable "ecs_autoscaling_max_capacity" {
  description = "Maximum number of tasks for model_train ECS service autoscaling."
  type        = number
  default     = 20
}

variable "ecs_autoscaling_target_cpu" {
  description = "Target average CPU utilization percentage for ECS autoscaling."
  type        = number
  default     = 70
}

variable "ecs_autoscaling_target_memory" {
  description = "Target average memory utilization percentage for ECS autoscaling."
  type        = number
  default     = 70
}

