variable "aws_region" {
  description = "AWS region where the training infrastructure will be deployed."
  type        = string
  default     = "us-east-1"
}

variable "project_name" {
  description = "Prefix used to name shared infrastructure resources."
  type        = string
  default     = "personalization"
}

variable "image_tag" {
  description = "Docker image tag generated by the CI pipeline and pushed to ECR."
  type        = string
}

variable "training_data_prefix" {
  description = "S3 prefix where events.csv and products.csv are stored."
  type        = string
  default     = "training-data"
}

variable "training_instance_type" {
  description = "SageMaker instance type used by the model_train job."
  type        = string
  default     = "t2.micro"
}

variable "model_package_group_name" {
  description = "SageMaker Model Registry group for purchase propensity models."
  type        = string
  default     = "purchase-propensity-model-group"
}

variable "trigger_training_pipeline" {
  description = "When true, starts a SageMaker pipeline execution during terraform apply."
  type        = bool
  default     = true
}
