variable "aws_region" {
  description = "AWS region where the training infrastructure will be deployed."
  type        = string
  default     = "us-east-1"
}

variable "project_name" {
  description = "Prefix used to name shared infrastructure resources."
  type        = string
  default     = "personalization"
}

variable "image_tag" {
  description = "Docker image tag generated by the CI pipeline and pushed to ECR."
  type        = string
}

variable "training_data_prefix" {
  description = "S3 prefix where events.csv and products.csv are stored."
  type        = string
  default     = "training-data"
}

variable "predictions_prefix" {
  description = "S3 prefix where model_predict writes prediction outputs."
  type        = string
  default     = "predictions"
}

variable "ecs_task_cpu" {
  description = "CPU units for the ECS Fargate tasks (4096 = 4 vCPU)."
  type        = string
  default     = "4096"
}

variable "ecs_task_memory" {
  description = "Memory in MiB for the ECS Fargate tasks (8192 = 8 GiB)."
  type        = string
  default     = "8192"
}

variable "model_package_group_name" {
  description = "SageMaker Model Registry group for purchase propensity models."
  type        = string
  default     = "purchase-propensity-model-group"
}

variable "recommendations_api_cpu" {
  description = "CPU units for the recommendations API Fargate tasks."
  type        = string
  default     = "512"
}

variable "recommendations_api_memory" {
  description = "Memory in MiB for the recommendations API Fargate tasks."
  type        = string
  default     = "1024"
}

variable "recommendations_api_desired_count" {
  description = "Initial desired task count for the recommendations API service."
  type        = number
  default     = 1
}

variable "recommendations_api_min_capacity" {
  description = "Minimum autoscaling capacity for the recommendations API service."
  type        = number
  default     = 1
}

variable "recommendations_api_max_capacity" {
  description = "Maximum autoscaling capacity for the recommendations API service."
  type        = number
  default     = 20
}
