"""Use case responsible for training the purchase propensity model."""

from dataclasses import dataclass

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from model_train.domain.entities.customer import Customer
from model_train.domain.utils.modeltrainerlogger import ModelTrainerLogger


@dataclass(frozen=True)
class TrainingResult:
    """Output produced after a successful model training run."""

    model: LogisticRegression
    scaler: StandardScaler
    metrics: dict[str, float]
    validated_customers: int


class ModelTrainer:
    """Train the purchase propensity model from validated feature data.

    This use case validates the training dataframe through ``Customer`` and then
    fits a ``StandardScaler`` plus ``LogisticRegression`` classifier. It does
    not perform I/O or AWS integration.
    """

    def __init__(
        self,
        test_size: float = 0.2,
        random_state: int = 42,
    ) -> None:
        """Initialize the trainer.

        Args:
            test_size: Fraction of rows reserved for offline evaluation.
            random_state: Random seed used by the train/test split.
        """
        self.test_size = test_size
        self.random_state = random_state
        self.logger = ModelTrainerLogger(self.__class__.__name__)

    def train(self, features: pd.DataFrame, labels: pd.Series) -> TrainingResult:
        """Validate features and train the purchase propensity model.

        Args:
            features: Training features generated by ``ModelHandler``.
            labels: Binary purchase labels aligned with ``features``.

        Returns:
            Trained model, fitted scaler and offline evaluation metrics.
        """
        self.logger.info(
            "training_started",
            rows=len(features),
            positive_labels=int(labels.sum()),
        )

        customers = Customer.validate_dataframe(features)
        self.logger.info(
            "training_features_validated",
            validated_customers=len(customers),
        )

        feature_matrix = features[Customer.FEATURE_COLUMNS].astype(float)
        x_train, x_test, y_train, y_test = train_test_split(
            feature_matrix,
            labels,
            test_size=self.test_size,
            random_state=self.random_state,
            stratify=labels,
        )

        scaler = StandardScaler()
        x_train_scaled = scaler.fit_transform(x_train)
        x_test_scaled = scaler.transform(x_test)

        model = LogisticRegression(max_iter=1000)
        model.fit(x_train_scaled, y_train)

        predictions = model.predict(x_test_scaled)
        probabilities = model.predict_proba(x_test_scaled)[:, 1]
        metrics = {
            "accuracy": float(accuracy_score(y_test, predictions)),
            "roc_auc": float(roc_auc_score(y_test, probabilities)),
        }

        self.logger.info(
            "training_completed",
            accuracy=metrics["accuracy"],
            roc_auc=metrics["roc_auc"],
            train_rows=len(x_train),
            test_rows=len(x_test),
        )

        return TrainingResult(
            model=model,
            scaler=scaler,
            metrics=metrics,
            validated_customers=len(customers),
        )
