"""Domain entity used to validate prediction features."""

from dataclasses import dataclass

import pandas as pd


@dataclass(frozen=True)
class Costumer:
    """Represent a user-product pair and validate its prediction features.

    This entity mirrors the feature contract expected by the purchase propensity
    model. ``FeatureEngineer`` materializes each row as a ``Costumer`` instance
    so invalid values are rejected before inference starts.
    """

    user_id: str
    product_id: str
    interactions: int
    price: float
    avg_rating: float
    popularity_score: float
    user_affinity_match: int

    FEATURE_COLUMNS = [
        "interactions",
        "price",
        "avg_rating",
        "popularity_score",
        "user_affinity_match",
    ]
    REQUIRED_COLUMNS = ["user_id", "product_id", *FEATURE_COLUMNS]

    def validate(self) -> None:
        """Validate the feature values for a single user-product pair.

        Raises:
            ValueError: If any feature violates the expected type or range.
        """
        if not self.user_id or not self.product_id:
            raise ValueError("user_id and product_id must not be empty")

        if self.interactions < 0:
            raise ValueError(f"interactions must be >= 0 for user {self.user_id}")

        if self.price <= 0:
            raise ValueError(f"price must be > 0 for product {self.product_id}")

        if not 0 <= self.avg_rating <= 5:
            raise ValueError(f"avg_rating must be between 0 and 5 for product {self.product_id}")

        if not 0 <= self.popularity_score <= 1:
            raise ValueError(
                f"popularity_score must be between 0 and 1 for product {self.product_id}"
            )

        if self.user_affinity_match not in (0, 1):
            raise ValueError(
                f"user_affinity_match must be 0 or 1 for user {self.user_id}"
            )

    @classmethod
    def from_row(cls, row: pd.Series) -> "Costumer":
        """Build a ``Costumer`` instance from a pandas row.

        Args:
            row: Single prediction row containing user and product features.

        Returns:
            Parsed ``Costumer`` entity ready for validation.
        """
        return cls(
            user_id=str(row["user_id"]),
            product_id=str(row["product_id"]),
            interactions=int(row["interactions"]),
            price=float(row["price"]),
            avg_rating=float(row["avg_rating"]),
            popularity_score=float(row["popularity_score"]),
            user_affinity_match=int(row["user_affinity_match"]),
        )

    @classmethod
    def validate_dataframe(cls, features: pd.DataFrame) -> list["Costumer"]:
        """Validate every row in the prediction feature dataframe.

        Args:
            features: Feature dataframe generated by ``FeatureEngineer``.

        Returns:
            List of validated ``Costumer`` entities.

        Raises:
            ValueError: If required columns are missing or any row is invalid.
        """
        missing_columns = [
            column for column in cls.REQUIRED_COLUMNS if column not in features.columns
        ]
        if missing_columns:
            raise ValueError(f"Missing required feature columns: {missing_columns}")

        costumers = [cls.from_row(row) for _, row in features.iterrows()]
        for costumer in costumers:
            costumer.validate()
        return costumers
